import { randomUUID } from 'node:crypto'
import type { IncomingMessage, ServerResponse } from 'node:http'
import { parse as parseUrl } from 'node:url'
import type { HandoffStore } from '../auth/handoff-store.js'
import type { OidcStateStore } from '../auth/state-store.js'
import type { KeyPairResult } from '../keys/manager.js'
import type { AuthProvider } from '../providers/interface.js'
import { createDamlToken } from '../tokens/issuer.js'
import type { RefreshTokenStore } from '../tokens/refresh.js'

const REFRESH_COOKIE_NAME = 'irsforge_refresh'

interface CallbackContext {
  provider: AuthProvider
  keys: KeyPairResult
  tokenStore: RefreshTokenStore
  /** Server-side state store; used to look up `orgId`+`nonce` by the opaque `state` URL param. */
  stateStore: OidcStateStore
  /** Short-lived store of fresh access tokens, keyed by an opaque handoff code. */
  handoffStore: HandoffStore
  issuer: string
  tokenTtlSeconds: number
  refreshTtlSeconds: number
  ledgerId: string
  applicationId: string
  /** Base URL (no trailing slash) to redirect to after a successful auth for a given org. */
  frontendUrlFor: (orgId: string) => string
  /** Base URL used for error redirects before orgId is known. */
  errorRedirectUrl: string
}

function errorHeaders(location: string): Record<string, string> {
  return {
    Location: location,
    'Cache-Control': 'no-store',
    'Referrer-Policy': 'no-referrer',
  }
}

export async function handleCallback(
  req: IncomingMessage,
  res: ServerResponse,
  ctx: CallbackContext,
): Promise<void> {
  const parsed = parseUrl(req.url ?? '', true)
  const code = parsed.query['code']
  const state = parsed.query['state']

  if (typeof code !== 'string' || typeof state !== 'string') {
    res.writeHead(302, errorHeaders(`${ctx.errorRedirectUrl}?error=auth_failed`))
    res.end()
    return
  }

  // CSRF defense: state must have been generated by us at /auth/authorize.
  // consume() is one-time-use and enforces TTL.
  const entry = ctx.stateStore.consume(state)
  if (!entry) {
    res.writeHead(302, errorHeaders(`${ctx.errorRedirectUrl}?error=invalid_state`))
    res.end()
    return
  }

  if (!ctx.provider.handleCallback) {
    res.writeHead(302, errorHeaders(`${ctx.errorRedirectUrl}?error=auth_failed`))
    res.end()
    return
  }

  let authResult: Awaited<ReturnType<NonNullable<AuthProvider['handleCallback']>>>

  try {
    authResult = await ctx.provider.handleCallback(code, entry.orgId, entry.nonce)
  } catch {
    res.writeHead(302, errorHeaders(`${ctx.errorRedirectUrl}?error=auth_failed`))
    res.end()
    return
  }

  const { userId, orgId, party, actAs, readAs } = authResult

  const accessToken = await createDamlToken(ctx.keys.privateKey, {
    userId,
    orgId,
    actAs,
    readAs,
    issuer: ctx.issuer,
    ttlSeconds: ctx.tokenTtlSeconds,
    ledgerId: ctx.ledgerId,
    applicationId: ctx.applicationId,
  })

  const refreshToken = ctx.tokenStore.create(userId, orgId, actAs, readAs)

  // Stash the JWT under an opaque one-time handoff code; the SPA will POST
  // the code to /auth/handoff to retrieve the JWT in a response body. This
  // keeps the JWT out of the URL bar, history, server logs, and Referer.
  const handoff = randomUUID()
  ctx.handoffStore.put(handoff, {
    accessToken,
    expiresIn: ctx.tokenTtlSeconds,
    userId,
    orgId,
    party,
  })

  const cookieValue = `${REFRESH_COOKIE_NAME}=${refreshToken}; HttpOnly; SameSite=Strict; Path=/auth; Max-Age=${ctx.refreshTtlSeconds}`

  const redirectUrl = `${ctx.frontendUrlFor(orgId)}/org/${orgId}/callback?handoff=${encodeURIComponent(handoff)}`

  res.writeHead(302, {
    'Set-Cookie': cookieValue,
    Location: redirectUrl,
    'Cache-Control': 'no-store',
    'Referrer-Policy': 'no-referrer',
  })
  res.end()
}
