import type { RateFamiliesConfig } from './schema-rate-families.js'

export interface CodegenScheduleEntry {
  frequencyMonths: number
  dayCountConvention: 'Act360' | 'Act365F'
}

export interface CodegenCsaEligible {
  currency: string
  haircut: number
}

export interface CodegenCsa {
  thresholdDirA: number
  thresholdDirB: number
  mta: number
  rounding: number
  valuationCcy: string
  eligibleCollateral: CodegenCsaEligible[]
}

export interface CodegenInput {
  currencies: Array<{ code: string; label: string; calendarId: string; isDefault: boolean }>
  cdsReferenceNames: string[]
  scheduleDefaults: Record<string, CodegenScheduleEntry>
  csa: CodegenCsa
  // Empty record under `profile: production` — the InitImpl seed treats `[]`
  // as "skip demo CSA funding".
  demoCsaInitialFunding: Record<string, number>
  schedulerPartyHint: string
  // Per-family operator co-sign policy seeded into Operator.Policy at bootstrap.
  // Ledger is the runtime source of truth; YAML is the seed only.
  operatorPolicy: Record<string, 'auto' | 'manual'>
}

/**
 * Convert a JS number to a Daml `Decimal` literal — preserves all significant
 * fraction digits and ensures the literal ends with a digit (Daml requires
 * `1.0`, not `1.`). Use everywhere a Decimal value is emitted.
 */
function damlDecimal(n: number): string {
  const s = n.toString()
  return s.includes('.') ? s : `${s}.0`
}

export function generateDamlConfig(input: CodegenInput): string {
  const defaults = input.currencies.filter((c) => c.isDefault)
  if (defaults.length !== 1) {
    throw new Error(`expected exactly one default currency, got ${defaults.length}`)
  }
  const currencyRows = input.currencies
    .map(
      (c) =>
        `    CurrencyDef with code = "${c.code}"; label = "${c.label}"; calendarId = "${c.calendarId}"`,
    )
    .join('\n  ,\n')

  const refNames = input.cdsReferenceNames.map((n) => `"${n}"`).join(', ')

  const scheduleRows = Object.entries(input.scheduleDefaults)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([key, e]) =>
        `    ("${key}", ScheduleDefaultsDef with frequencyMonths = ${e.frequencyMonths}; dayCountConvention = ${e.dayCountConvention})`,
    )
    .join('\n  ,\n')

  const eligibleEntries = input.csa.eligibleCollateral
    .map((e) => `("${e.currency}", ${damlDecimal(e.haircut)})`)
    .join(', ')
  const fundingEntries = Object.entries(input.demoCsaInitialFunding)
    .map(([c, v]) => `("${c}", ${damlDecimal(v)})`)
    .join(', ')

  const policyRows = Object.entries(input.operatorPolicy)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([family, mode]) => `    ("${family}", ${mode === 'manual' ? 'Manual' : 'Auto'})`)
    .join('\n  ,\n')

  return `-- AUTO-GENERATED by shared-config/scripts/generate-daml-config.ts. DO NOT EDIT.
module Setup.GeneratedConfig where

import Daml.Finance.Interface.Types.Date.V3.DayCount (DayCountConventionEnum(..))
import Operator.Policy (PolicyMode(..))

data CurrencyDef = CurrencyDef
  with
    code       : Text
    label      : Text
    calendarId : Text
  deriving (Eq, Show)

configuredCurrencies : [CurrencyDef]
configuredCurrencies =
  [
${currencyRows}
  ]

defaultCurrencyCode : Text
defaultCurrencyCode = "${defaults[0].code}"

cdsReferenceNames : [Text]
cdsReferenceNames = [${refNames}]

data ScheduleDefaultsDef = ScheduleDefaultsDef
  with
    frequencyMonths    : Int
    dayCountConvention : DayCountConventionEnum
  deriving (Eq, Show)

scheduleDefaultsEntries : [(Text, ScheduleDefaultsDef)]
scheduleDefaultsEntries =
  [
${scheduleRows}
  ]

csaThresholdDirA : Decimal
csaThresholdDirA = ${damlDecimal(input.csa.thresholdDirA)}

csaThresholdDirB : Decimal
csaThresholdDirB = ${damlDecimal(input.csa.thresholdDirB)}

csaMta : Decimal
csaMta = ${damlDecimal(input.csa.mta)}

csaRounding : Decimal
csaRounding = ${damlDecimal(input.csa.rounding)}

csaValuationCcy : Text
csaValuationCcy = "${input.csa.valuationCcy}"

csaEligibleCollateral : [(Text, Decimal)]
csaEligibleCollateral = [${eligibleEntries}]

demoCsaInitialFunding : [(Text, Decimal)]
demoCsaInitialFunding = [${fundingEntries}]

schedulerPartyHint : Text
schedulerPartyHint = "${input.schedulerPartyHint}"

operatorPolicySeeds : [(Text, PolicyMode)]
operatorPolicySeeds =
  [
${policyRows}
  ]
`
}

function damlTextList(items: string[]): string {
  if (items.length === 0) return '[]'
  return `[ ${items.map((s) => `"${s}"`).join('\n  , ')}\n  ]`
}

export function generateRateFamiliesDaml(families: RateFamiliesConfig): string {
  // Identifier names mirror the legacy `Constants.daml` shape (sofrIndexRateId,
  // sofrOvernightRateId, sofrTenorRateIds) so existing Daml importers migrate
  // by swapping the import path only — no symbol renames.
  const blocks = Object.entries(families)
    .map(([name, f]) => {
      const prefix = name.toLowerCase()
      const tenorIds = f.tenors.map((t) => t.id)
      return `${prefix}IndexRateId : Text
${prefix}IndexRateId = "${f.curveIndexId}"

${prefix}OvernightRateId : Text
${prefix}OvernightRateId = "${f.overnightIndexId}"

${prefix}TenorRateIds : [Text]
${prefix}TenorRateIds = ${damlTextList(tenorIds)}`
    })
    .join('\n\n')

  return `-- AUTO-GENERATED by shared-config. DO NOT EDIT.
module Setup.GeneratedRateFamilies where

${blocks}
`
}

export function generateRateFamiliesTs(families: RateFamiliesConfig): string {
  // Identifier names mirror the legacy oracle/providers/nyfed/constants.ts
  // shape (SOFR_INDEX_RATE_ID, SOFR_OVERNIGHT_RATE_ID, SOFR_TENOR_RATE_IDS,
  // TENOR_DAYS) so existing TS importers migrate by swapping the import path
  // only — no symbol renames.
  const blocks = Object.entries(families)
    .map(([name, f]) => {
      const upper = name.toUpperCase()
      const ids = f.tenors.map((t) => `'${t.id}'`).join(', ')
      const days = f.tenors.map((t) => `  '${t.id}': ${t.days},`).join('\n')
      return `export const ${upper}_INDEX_RATE_ID = '${f.curveIndexId}' as const
export const ${upper}_OVERNIGHT_RATE_ID = '${f.overnightIndexId}' as const
export const ${upper}_TENOR_RATE_IDS = [${ids}] as const
export const ${upper}_TENOR_DAYS: Record<string, number> = {
${days}
}`
    })
    .join('\n\n')

  return `// AUTO-GENERATED by shared-config. DO NOT EDIT.
${blocks}
`
}
