import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)

interface FixtureQuery {
  tenorDays: number
  expectedZero: string
}

interface FixtureCase {
  name: string
  pillars: Array<{ tenorDays: number; zeroRate: string }>
  dayCount: string
  interpolation: string
  queries: FixtureQuery[]
}

interface Fixture {
  cases: FixtureCase[]
}

if (process.argv[1] === __filename) {
  const fixturePath = resolve(dirname(__filename), '../src/fixtures/curve-interpolation.json')
  const fixture: Fixture = JSON.parse(readFileSync(fixturePath, 'utf8'))

  const lines: string[] = [
    '-- AUTO-GENERATED by shared-config/scripts/generate-fixture-daml.ts. DO NOT EDIT.',
    'module Oracle.FixtureData where',
    '',
    'import Oracle.Types (InterpolationMethod(..), CurveDayCount(..), Pillar(..))',
    '',
    'data FixtureQuery = FixtureQuery',
    '  with',
    '    tenorDays : Int',
    '    expectedZero : Decimal',
    '  deriving (Eq, Show)',
    '',
    'data FixtureCase = FixtureCase',
    '  with',
    '    name : Text',
    '    pillars : [Pillar]',
    '    dayCount : CurveDayCount',
    '    interpolation : InterpolationMethod',
    '    queries : [FixtureQuery]',
    '  deriving (Eq, Show)',
    '',
    'fixtureCases : [FixtureCase]',
    'fixtureCases =',
  ]

  const caseStrs = fixture.cases.map((c) => {
    const pillars = c.pillars
      .map((p) => `Pillar with tenorDays = ${p.tenorDays}; zeroRate = ${p.zeroRate}`)
      .join('\n      , ')
    const queries = c.queries
      .map((q) => `FixtureQuery with tenorDays = ${q.tenorDays}; expectedZero = ${q.expectedZero}`)
      .join('\n      , ')
    return [
      `  FixtureCase with`,
      `    name = "${c.name}"`,
      `    pillars = [${pillars}]`,
      `    dayCount = ${c.dayCount}`,
      `    interpolation = ${c.interpolation}`,
      `    queries = [${queries.length > 0 ? queries : ''}]`,
    ].join('\n')
  })

  lines.push(`  [${caseStrs.join('\n  ,')}\n  ]`)

  const target = resolve(dirname(__filename), '../../contracts/src/Oracle/FixtureData.daml')
  writeFileSync(target, `${lines.join('\n')}\n`, 'utf8')
  console.log(`[codegen] wrote ${target}`)
}
