// Pre-qualified Daml template IDs for the oracle.
//
// Canton's JSON API requires `<packageId>:<module>:<entity>` (two colons);
// passing the bare `<module>:<entity>` form returns a 400 with
// "did not have two ':' chars". The oracle used to do the bare form
// everywhere, which meant every seed + every admin endpoint 401/400d
// against a live sandbox (surfaced by the Phase 3 Stage B smoke test).
//
// Every call site imports from here rather than writing a literal string;
// the package IDs are auto-generated by scripts/gen-package-ids.sh.
import {
  DAML_FINANCE_DATA_PACKAGE_ID,
  DAML_FINANCE_HOLDING_PACKAGE_ID,
  DAML_FINANCE_INSTRUMENT_SWAP_PACKAGE_ID,
  DAML_FINANCE_LIFECYCLE_PACKAGE_ID,
  IRSFORGE_PACKAGE_ID,
} from './generated/package-ids.js'

// IRSForge-authored templates (Oracle.*, Setup.*, Swap.*)
export const NYFED_PROVIDER_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Oracle.NYFedProvider:NYFedOracleProvider`
export const DEMO_STUB_PROVIDER_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Oracle.DemoStubProvider:DemoStubOracleProvider`
export const FLOATING_RATE_INDEX_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Oracle.FloatingRateIndex:FloatingRateIndex`
export const CURVE_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Oracle.Curve:Curve`
export const CURVE_SNAPSHOT_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Oracle.CurveSnapshot:CurveSnapshot`
export const NYFED_OBSERVATION_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Oracle.NYFedProvider:NYFedObservation`
export const FX_SPOT_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Oracle.FxSpot:FxSpot`

// Daml Finance templates. Oracle mints these from NYFedOracleProvider
// and DemoStubOracleProvider choices; the observation template lives in
// the daml-finance-data package.
export const DAML_FINANCE_OBSERVATION_TEMPLATE_ID = `${DAML_FINANCE_DATA_PACKAGE_ID}:Daml.Finance.Data.V4.Numeric.Observation:Observation`

// Phase 5 Stage A — IRSForge-native CSA / Mark / Shortfall templates.
// The oracle's MarkScheduler (Stage B) writes MarkToMarket contracts
// against Csa contracts; pre-qualifying with the IRSForge package ID
// follows the same pattern as the Oracle.* constants above.
export const CSA_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Csa.Csa:Csa`
export const MARK_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Csa.Mark:MarkToMarket`
export const SHORTFALL_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Csa.Shortfall:MarginShortfall`

// Tier 2 #8 — per-dispute audit-trail contract. Created when a CSA
// dispute opens (via `Dispute` choice), archived on resolution
// (via `AcknowledgeDispute` or `AgreeToCounterMark`).
export const CSA_DISPUTE_RECORD_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Csa.Dispute:DisputeRecord`

// SwapWorkflow is the orchestration contract Phase 5 Stage B's mark
// publisher groups by (partyA, partyB) to form netting sets. Defined in
// contracts/src/Swap/Workflow.daml; lives in the IRSForge DAR.
export const SWAP_WORKFLOW_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Swap.Workflow:SwapWorkflow`

// Phase 6 Stage A — scheduler role marker + NettedBatch audit row.
export const SCHEDULER_ROLE_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Setup.SchedulerRole:SchedulerRole`
export const NETTED_BATCH_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Csa.Netting:NettedBatch`

// Phase 6 Stage C2 — scheduler-service setup + lifecycle plumbing.
// CashSetupRecord is the directory contract the scheduler reads once at
// boot to discover the scheduler-authorized LifecycleRule, settlement
// factory, route provider, event factory, and party account keys.
export const CASH_SETUP_RECORD_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Setup.CashSetup:CashSetupRecord`
export const EVENT_FACTORY_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Setup.EventFactory:EventFactory`
export const MATURED_SWAP_TEMPLATE_ID = `${IRSFORGE_PACKAGE_ID}:Swap.Workflow:MaturedSwap`

// Daml Finance templates the scheduler queries / creates directly.
export const DAML_FINANCE_EFFECT_TEMPLATE_ID = `${DAML_FINANCE_LIFECYCLE_PACKAGE_ID}:Daml.Finance.Lifecycle.V4.Effect:Effect`
export const DATE_CLOCK_UPDATE_EVENT_TEMPLATE_ID = `${DAML_FINANCE_DATA_PACKAGE_ID}:Daml.Finance.Data.V4.Time.DateClockUpdate:DateClockUpdateEvent`

// Per-family swap-instrument template IDs — the scheduler reads each
// instrument's `lastEventTimestamp` + maturity date directly so it
// knows when to next fire a lifecycle event and when to retire.
export const IRS_INSTRUMENT_TEMPLATE_ID = `${DAML_FINANCE_INSTRUMENT_SWAP_PACKAGE_ID}:Daml.Finance.Instrument.Swap.V0.InterestRate.Instrument:Instrument`
export const CDS_INSTRUMENT_TEMPLATE_ID = `${DAML_FINANCE_INSTRUMENT_SWAP_PACKAGE_ID}:Daml.Finance.Instrument.Swap.V0.CreditDefault.Instrument:Instrument`
export const CCY_INSTRUMENT_TEMPLATE_ID = `${DAML_FINANCE_INSTRUMENT_SWAP_PACKAGE_ID}:Daml.Finance.Instrument.Swap.V0.Currency.Instrument:Instrument`
export const FX_INSTRUMENT_TEMPLATE_ID = `${DAML_FINANCE_INSTRUMENT_SWAP_PACKAGE_ID}:Daml.Finance.Instrument.Swap.V0.ForeignExchange.Instrument:Instrument`
export const ASSET_INSTRUMENT_TEMPLATE_ID = `${DAML_FINANCE_INSTRUMENT_SWAP_PACKAGE_ID}:Daml.Finance.Instrument.Swap.V0.Asset.Instrument:Instrument`
export const FPML_INSTRUMENT_TEMPLATE_ID = `${DAML_FINANCE_INSTRUMENT_SWAP_PACKAGE_ID}:Daml.Finance.Instrument.Swap.V0.Fpml.Instrument:Instrument`

// TransferableFungible holding template — used by holdings-resolver to
// find per-ccy + per-party holdings for SettleNetByScheduler.
export const TRANSFERABLE_FUNGIBLE_TEMPLATE_ID = `${DAML_FINANCE_HOLDING_PACKAGE_ID}:Daml.Finance.Holding.V4.TransferableFungible:TransferableFungible`

export const SWAP_INSTRUMENT_TEMPLATE_BY_TYPE: Record<string, string> = {
  IRS: IRS_INSTRUMENT_TEMPLATE_ID,
  OIS: IRS_INSTRUMENT_TEMPLATE_ID,
  CDS: CDS_INSTRUMENT_TEMPLATE_ID,
  CCY: CCY_INSTRUMENT_TEMPLATE_ID,
  FX: FX_INSTRUMENT_TEMPLATE_ID,
  ASSET: ASSET_INSTRUMENT_TEMPLATE_ID,
  FpML: FPML_INSTRUMENT_TEMPLATE_ID,
}
