#!/usr/bin/env bash
# Extract main package IDs from a declared list of DARs and write them
# as TypeScript constants consumed by app/src/shared/ledger.
#
# Invoked by `make gen-package-ids` after `daml build`.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Bootstrap PATH/JAVA_HOME the same way daml-quiet.sh and demo.sh do, so
# `make gen-package-ids` works in non-interactive shells (CI, fresh
# terminals). Without this the `command -v daml` preflight below misses
# $HOME/.daml/bin and exits with a misleading "not found" error.
# shellcheck source=lib/daml-env.sh
. "$SCRIPT_DIR/lib/daml-env.sh"
# `scripts/daml-quiet.sh` silences the Daml 2.10.x assistant's "outdated
# version" warning — it advertises Daml 3.x, an incompatible rewrite we
# can't adopt while pinned to Daml Finance v4 / Canton 2.x. See that file
# for the full rationale.
DAML_QUIET="$SCRIPT_DIR/daml-quiet.sh"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Same constants emitted twice so Next.js (app) and tsx (oracle) can both
# import them without crossing workspace boundaries. Any new DAR added to
# PAIRS lands in both files on the next gen-package-ids run.
OUT_DIR="$REPO_ROOT/app/src/shared/ledger/generated"
OUT_FILE="$OUT_DIR/package-ids.ts"
ORACLE_OUT_DIR="$REPO_ROOT/oracle/src/shared/generated"
ORACLE_OUT_FILE="$ORACLE_OUT_DIR/package-ids.ts"

# Declared list of (DAR relative path, TS constant name) pairs.
# Add new entries here when the frontend needs another package's ID.
# Format: "<relative-path><TAB><CONSTANT_NAME>"
PAIRS=(
	"contracts/.daml/dist/irsforge-contracts-0.0.1.dar	IRSFORGE_PACKAGE_ID"
	"contracts/lib/daml-finance-data-v4-4.0.0.dar	DAML_FINANCE_DATA_PACKAGE_ID"
	"contracts/lib/daml-finance-lifecycle-v4-4.0.0.dar	DAML_FINANCE_LIFECYCLE_PACKAGE_ID"
	"contracts/lib/daml-finance-holding-v4-4.0.0.dar	DAML_FINANCE_HOLDING_PACKAGE_ID"
	"contracts/lib/daml-finance-claims-v3-3.0.0.dar	DAML_FINANCE_CLAIMS_PACKAGE_ID"
	"contracts/lib/daml-finance-instrument-swap-v0-0.5.0.dar	DAML_FINANCE_INSTRUMENT_SWAP_PACKAGE_ID"
)

# Preflight: required tools.
if ! command -v daml >/dev/null 2>&1; then
  echo "error: 'daml' not found on PATH. Install the Daml SDK (see make setup)." >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "error: 'jq' not found on PATH. Install with 'brew install jq'." >&2
  exit 1
fi

mkdir -p "$OUT_DIR" "$ORACLE_OUT_DIR"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "// AUTO-GENERATED by scripts/gen-package-ids.sh — do not edit."
  echo "// Regenerate with \`make gen-package-ids\` after \`daml build\`."
} > "$TMP"

for pair in "${PAIRS[@]}"; do
  REL="${pair%%	*}"     # before the tab
  NAME="${pair##*	}"    # after the tab
  DAR="$REPO_ROOT/$REL"
  if [[ ! -f "$DAR" ]]; then
    echo "error: DAR not found at $DAR (entry: $NAME). Run 'cd contracts && daml build' or restore lib DAR." >&2
    exit 1
  fi
  # Run damlc from contracts/ so the assistant resolves SDK version via
  # contracts/daml.yaml (sdk-version: 2.10.4). Without this, machines with
  # SDK 3.x also installed (default for new projects) invoke 3.x's damlc
  # from the repo root, which rejects LF 1.x DARs with
  # 'ParseError "Lf1 is not supported"'.
  PKG_ID="$(cd "$REPO_ROOT/contracts" && "$DAML_QUIET" damlc inspect-dar --json "$DAR" | jq -r '.main_package_id')"
  if [[ -z "$PKG_ID" || "$PKG_ID" == "null" ]]; then
    echo "error: main_package_id missing from $DAR (entry: $NAME)." >&2
    exit 1
  fi
  echo "export const $NAME = \"$PKG_ID\";" >> "$TMP"
  echo "  $NAME = $PKG_ID"
done

# Derived: full template id for the Oracle.Interface:Provider interface.
# TS callers exercise interface choices via this id (Tasks 6-10 of the
# oracle-provider-pluggability plan).
{
  echo ""
  echo "export const IRSFORGE_PROVIDER_INTERFACE_ID = \`\${IRSFORGE_PACKAGE_ID}:Oracle.Interface:Provider\`;"
} >> "$TMP"

# Emit identical constants for the oracle. It runs under tsx so TS imports
# work the same way the app's do; we just need a sibling generated file
# for workspace-boundary clean imports.
cp "$TMP" "$ORACLE_OUT_FILE"
mv "$TMP" "$OUT_FILE"
trap - EXIT
echo "wrote $OUT_FILE"
echo "wrote $ORACLE_OUT_FILE"
